spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lizi_wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: lizi
        password: regexOne@123

springfox:
    documentation:
        swagger-ui:
            enabled: true